# Generated by Django 2.0.2 on 2020-12-04 12:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student_module', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=50)),
                ('Question_Paper', models.FileField(upload_to='Question')),
                ('Semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('Branch', models.CharField(max_length=20)),
                ('Section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('Subject', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('Branch', models.CharField(max_length=20)),
                ('Section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('Student_Name', models.CharField(blank=True, max_length=20)),
                ('Answer_Sheet', models.FileField(blank=True, upload_to='Answer')),
                ('Assignment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_module.Assignment')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_module.Student_General_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('Branch', models.CharField(max_length=20)),
                ('Section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('Subject', models.CharField(max_length=15)),
                ('Notes', models.FileField(upload_to='Notes')),
                ('Description', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Academy_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=15)),
                ('Semester', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('Branch', models.CharField(max_length=20)),
                ('Section', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_General_Info',
            fields=[
                ('Teacher_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Teacher_Phone_Number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be correct Add 0 at starting', regex='^(0)+\\d{10}$')])),
                ('Address', models.TextField(max_length=50)),
                ('Qualification', models.CharField(max_length=20)),
                ('Photo', models.ImageField(blank=True, default='Photo/default.jpg', upload_to='photo')),
            ],
        ),
        migrations.AddField(
            model_name='teacher_academy_info',
            name='teacher_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_module.Teacher_General_Info'),
        ),
        migrations.AddField(
            model_name='student_notes',
            name='Teacher_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_module.Teacher_General_Info'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Teacher_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_module.Teacher_General_Info'),
        ),
    ]
