# Generated by Django 2.0.2 on 2020-12-04 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Academy_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('Section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('Branch', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student_General_Info',
            fields=[
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Roll_No', models.IntegerField()),
                ('Name', models.CharField(max_length=30)),
                ('Father_Name', models.CharField(max_length=30)),
                ('Date_Of_Birth', models.DateField()),
                ('Father_Phone_Number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be correct Add 0 at starting', regex='^(0)+\\d{10}$')])),
                ('Alternate_Number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be correct Add 0 at starting', regex='^(0)+\\d{10}$')])),
                ('Address', models.TextField(max_length=255)),
                ('Photo', models.ImageField(blank=True, default='Photo/default.jpg', upload_to='Photo')),
                ('Blood_Group', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='student_academy_info',
            name='student_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Student_module.Student_General_Info'),
        ),
    ]
